### ISSUE TITLE
color image - color bar doesn't return to original colored image

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#10]
When importing a color image, it is unclear how to return to the original color image.
When a color image is imported, and 'IsColor' is activated, only the grayscale image can be displayed.

**Comment by radjkarl** [comment]
Solved in commit/425e9e997a5ea72305c10adfdbe4acde6a52bf88
Click on the 'undo' button or ctrl+z to undo transform back to RBG
