### ISSUE TITLE
Export appends closing parenthesis

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#14]
In Linux, export from toolbar (png, bmp) appends a ")" at the end of the file, so instead of "output.bmp" you get "output.bmp)"

Does not appear in Windows version.

Error in pyqtgraph ImageExporter?

**Comment by radjkarl** [comment]
No - error was in the way file type were appended to file paths ... fixed, see: 
https://github.com/radjkarl/fancyWidgets/commit/ffe0d5747c5296c78575f0e0909af915a4a5698f
