### ISSUE TITLE
Unable to find "Series resistance" (R_s) 

### ISSUE THREAD

**Issue by JonasRW** [radjkarl/dataArtist#24]
Hello,

Thanks al lot for his very helpful software!
I recently downloaded the dataArtist (Win10-7 24/Feb/2018) Version. In that, I am unable to find the "Series resistance" Tab. I also looked at the docs and coulden't fine it there either. Is this something you have removed? If so, can i aske why?
Thanks in advance!

Best regardes,
Jonas

**Comment by JonasRW** [comment]
So for the conclusions in the paper "QUANTITATIVE ELECTROLUMINESCENCE MEASUREMENTS OF PV DEVICES" about series resistances. Is it still possible to create series resistance maps, or is it not possible to differentiate between shunst and series?

**Comment by radjkarl** [comment]
I suggest to not follow the methods based on 2 EL images to extract series
resistance maps.
Just ask yourself, why never results on module scale where compared to LBIC
maps.
