### ISSUE TITLE
Right click on color bar to non-default color scheme hides image

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#5]
Right click on color bar cannot change from default setting.  Both on Windows 7 and Ubuntu 16.04. Resulting image is blank.

Error message is 'could not broadcast input array from shape'

Version 0.10.1

**Comment by openclipboard** [comment]
Solution is to make sure the 'IsColor' button on the toolbar is deactivated.  If it is active, the resulting image is black.   If inactive, the resulting image is correctly displayed.

**Comment by openclipboard** [comment]
Would be good to either make this automatically switch over, or offer a warning.

**Comment by radjkarl** [comment]
solved:
https://github.com/radjkarl/pyqtgraph/commit/13d82f38d47dc7ab50412a3581927e8b4cd351be
