### ISSUE TITLE
Linux - Title cannot be entered in Preferences

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#7]
On Linux version (Ubuntu 16.04), title cannot be entered in Preferences.

**Comment by radjkarl** [comment]
hmm ... works for me(Mint 18,cinnamon 64bit) , see:
![image](https://cloud.githubusercontent.com/assets/350050/26225675/5ba59038-3c20-11e7-8861-a35d82cf5e58.png)

can you give more details?

**Comment by openclipboard** [comment]
Hmmm... doesn't work for me in Ubuntu 16.04.

Entry in other areas (i.e., units) is not allowed either, nor is the console allowing input.

Works fine in Windows.

**Comment by radjkarl** [comment]
close it for now since it works on the win exec and on my linuxMint exec
