### ISSUE TITLE
Scaling/Offset issues

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#9]
Scaling in a graph works, but offset doesn't seem to work.

**Comment by radjkarl** [comment]
example please

**Comment by openclipboard** [comment]
Here is an example; scaling is OK, but offset value does not change X-axis.

![image](https://cloud.githubusercontent.com/assets/28735151/26249186/7ac8dea4-3c73-11e7-8fc1-f33f1d00fc70.png)

**Comment by radjkarl** [comment]
I removed the offset parameter for all non stack axes - scaling is needed - offset ... well you can set this in your data (for now).
i also simplified the axes parameter menu a bit:
![image](https://cloud.githubusercontent.com/assets/350050/26276798/79886a74-3d76-11e7-9360-eded66de1c21.png)

see: https://github.com/radjkarl/dataArtist/commit/d43bd59be89701bd4ce4d35b1a84759fa7754027
